[versions]

paper = "1.20-R0.1-SNAPSHOT"
kotlin = "2.1.20"
kotlinx-binaryCompatibilityValidator = "0.17.0"
kotlinx-serialization = "1.8.1"
dokka = "1.9.10"
annotations = "26.0.2"

commandapi = "9.7.0"
bstats = "3.1.0"

skillapi = "3.102"
battlelevels = "6.9.1"
mmocore = "1.12.1-SNAPSHOT"
mmoitems = "6.9.5-SNAPSHOT"
mythiclib = "1.6.2-SNAPSHOT"
heroes = "1.9.30-RELEASE"

junit = "5.10.1"
kotest = "5.8.0"
mockk = "1.13.8"

gradlePlugin-bukkitgradle = "1.0.0"
gradlePlugin-shadow = "8.1.1"
gradlePlugin-versions = "0.50.0"

[libraries]

paperApi = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
serialization-hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "kotlinx-serialization" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

commandapi = { module = "dev.jorel:commandapi-bukkit-core", version.ref = "commandapi" }
commandapi-kotlin = { module = "dev.jorel:commandapi-bukkit-kotlin", version.ref = "commandapi" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

rpgplugins-skillapi = { module = "com.sucy:SkillAPI", version.ref = "skillapi" }
rpgplugins-battlelevels = { module = "me.robin:BattleLevels", version.ref = "battlelevels" }
rpgplugins-mmocore = { module = "net.Indyuce:MMOCore-API", version.ref = "mmocore" }
rpgplugins-mmoitems = { module = "net.Indyuce:MMOItems-API", version.ref = "mmoitems" }
rpgplugins-mythiclib = { module = "io.lumine:MythicLib-dist", version.ref = "mythiclib" }
rpgplugins-heroes = { module = "com.herocraftonline.heroes:Heroes", version.ref = "heroes" }

# Test dependencies
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# Build dependencies
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinx-binaryCompatibilityValidator" }

[plugins]

bukkitgradle = { id = "ru.endlesscode.bukkitgradle", version.ref = "gradlePlugin-bukkitgradle" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "gradlePlugin-shadow" }
versions = { id = "com.github.ben-manes.versions", version.ref = "gradlePlugin-versions" }

[bundles]

rpgplugins = [
    "rpgplugins-skillapi",
    "rpgplugins-battlelevels",
    "rpgplugins-mmocore",
    "rpgplugins-mmoitems",
    "rpgplugins-mythiclib",
    "rpgplugins-heroes",
]
