name: Publish

on:
  push:
    tags: [ v* ]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: temurin

      - name: Assemble Plugin
        uses: eskatos/gradle-command-action@v2
        with:
          arguments: :mimic-bukkit:shadowJar

      - name: Copy plugin to root directory
        run: cp ./mimic-bukkit/build/libs/*-all.jar Mimic.jar

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Mimic ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Plugin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./Mimic.jar
          asset_name: Mimic-${{ github.ref }}.jar
          asset_content_type: application/java-archive
