name: Publish

on:
  push:
    tags: [ v* ]

jobs:
  bintray:
    name: Publish to Bintray
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Upload to Bintray
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: bintrayUpload
      env:
        BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Assemble Plugin
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble
      - name: Copy plugin to root directory
        run: |
          ls -la ./mimic-bukkit/build/libs/
          cp ./mimic-bukkit/build/libs/*-all.jar Mimic.jar
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Plugin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./Mimic.jar
          asset_name: Mimic-${{ github.ref }}.jar
          asset_content_type: application/java-archive
